apiVersion: v1
kind: Service
metadata:
  name: geospecialistsid-service
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 0.0.0.0/0
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: geospecialistsid
